name       : libhtp
version    : 0.5.39
release    : 7
source     :
    - https://github.com/OISF/libhtp/archive/refs/tags/0.5.39.tar.gz : d5956b49314fc6a058864130fbcf040a12584ee1e38f3b6ea52aedfa99d4c14a
license    : BSD-3-Clause
component  : security.crypto
summary    : LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces
description: |
    LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
