name       : libhtp
version    : 0.5.27
release    : 2
source     :
    - https://github.com/OISF/libhtp/archive/0.5.27.tar.gz : 3a44cde5bd982005834c4ec4d86cff701796dd337cb471dbc1bc417880eaa161
license    : BSD-3-Clause
component  : security.crypto
summary    : LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces
description: |
    LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
