name       : libhtp
version    : 0.5.33
release    : 5
source     :
    - https://github.com/OISF/libhtp/archive/0.5.33.tar.gz : 953651fdfe828805bb82dc1aa8b56187b0e2f80781727343e68ccf8afd6a9122
license    : BSD-3-Clause
component  : security.crypto
summary    : LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces
description: |
    LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
