name       : libhtp
version    : 0.5.30
release    : 3
source     :
    - https://github.com/OISF/libhtp/archive/0.5.30.tar.gz : 7384f8461ad0431e9247c49b37a73929b284f39408d1f11b80949b188069b638
license    : BSD-3-Clause
component  : security.crypto
summary    : LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces
description: |
    LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
