name       : libhtp
version    : 0.5.38
release    : 6
source     :
    - https://github.com/OISF/libhtp/archive/refs/tags/0.5.38.tar.gz : 8365f338fdf5ef0f3b37f3cb4e2670d218c843eccc42aa87119819c0f018ef39
license    : BSD-3-Clause
component  : security.crypto
summary    : LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces
description: |
    LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
